#include <stdio.h>
int main()
{
    FILE *fp;
    fp = fopen("练习5-1	求m到n之和.c", "w");
    fclose(fp);
    fp = fopen("练习5-2	找两个数中最大者.c", "w");
    fclose(fp);
    fp = fopen("练习5-3	数字金字塔.c", "w");
    fclose(fp);
    fp = fopen("习题5-1	符号函数.c", "w");
    fclose(fp);
    fp = fopen("习题5-2	使用函数求奇数和.c", "w");
    fclose(fp);
    fp = fopen("习题5-3	使用函数计算两点间的距离.c", "w");
    fclose(fp);
    fp = fopen("习题5-4	使用函数求素数和.c", "w");
    fclose(fp);
    fp = fopen("习题5-5	使用函数统计指定数字的个数.c", "w");
    fclose(fp);
    fp = fopen("习题5-6	使用函数输出水仙花数.c", "w");
    fclose(fp);
    fp = fopen("习题5-7	使用函数求余弦函数的近似值.c", "w");
    fclose(fp);
    fp = fopen("习题6-1	分类统计字符个数.c", "w");
    fclose(fp);
    fp = fopen("习题6-2	使用函数求特殊a串数列和.c", "w");
    fclose(fp);
    fp = fopen("习题6-3	使用函数输出指定范围内的完数.c", "w");
    fclose(fp);
    fp = fopen("习题6-4	使用函数输出指定范围内的Fibonacci数.c", "w");
    fclose(fp);
    fp = fopen("习题6-5	使用函数验证哥德巴赫猜想.c", "w");
    fclose(fp);
    fp = fopen("习题6-6	使用函数输出一个整数的逆序数.c", "w");
    fclose(fp);
    fp = fopen("练习8-2	计算两数的和与差.c", "w");
    fclose(fp);
    fp = fopen("练习8-8	移动字母.c", "w");
    fclose(fp);
    fp = fopen("习题8-1	拆分实数的整数与小数部分.c", "w");
    fclose(fp);
    fp = fopen("习题8-2	在数组中查找指定元素.c", "w");
    fclose(fp);
    fp = fopen("习题8-3	数组循环右移.c", "w");
    fclose(fp);
    fp = fopen("习题8-4	报数.c", "w");
    fclose(fp);
    fp = fopen("习题8-5	使用函数实现字符串部分复制.c", "w");
    fclose(fp);
    fp = fopen("习题8-6	删除字符.c", "w");
    fclose(fp);
    fp = fopen("习题8-8	判断回文字符串.c", "w");
    fclose(fp);
    fp = fopen("习题8-9	分类统计各类字符个数.c", "w");
    fclose(fp);
    fp = fopen("习题9-2	计算两个复数之积.c", "w");
    fclose(fp);
    fp = fopen("习题9-6	按等级统计学生成绩.c", "w");
    fclose(fp);
    fp = fopen("练习10-1 使用递归函数计算1到n之和.c", "w");
    fclose(fp);
    fp = fopen("习题10-1 判断满足条件的三位数.c", "w");
    fclose(fp);
    fp = fopen("习题10-2 递归求阶乘和.c", "w");
    fclose(fp);
    fp = fopen("习题10-3 递归实现指数函数.c", "w");
    fclose(fp);
    fp = fopen("习题10-4 递归求简单交错幂级数的部分和.c", "w");
    fclose(fp);
    fp = fopen("习题10-5 递归计算Ackermenn函数.c", "w");
    fclose(fp);
    fp = fopen("习题10-6 递归求Fabonacci数列.c", "w");
    fclose(fp);
    fp = fopen("习题10-7 十进制转换二进制.c", "w");
    fclose(fp);
    fp = fopen("习题10-8 递归实现顺序输出整数.c", "w");
    fclose(fp);
    fp = fopen("习题11-1 输出月份英文名.c", "w");
    fclose(fp);
    fp = fopen("习题11-2 查找星期.c", "w");
    fclose(fp);
    fp = fopen("习题11-3 计算最长的字符串长度.c", "w");
    fclose(fp);
    fp = fopen("习题11-4 字符串的连接.c", "w");
    fclose(fp);
    fp = fopen("习题11-5 指定位置输出字符串.c", "w");
    fclose(fp);
    fp = fopen("习题11-6 查找子串.c", "w");
    fclose(fp);
    fp = fopen("习题11-7 奇数值结点链表.c", "w");
    fclose(fp);
    fp = fopen("习题11-8 单链表结点删除.c", "w");
    fclose(fp);

    fp = fopen("练习2-1	Programming in C is fun!.c", "w");
    fclose(fp);
    fp = fopen("练习2-3	输出倒三角图案.c", "w");
    fclose(fp);
    fp = fopen("练习2-4	温度转换.c", "w");
    fclose(fp);
    fp = fopen("练习2-6	计算物体自由下落的距离.c", "w");
    fclose(fp);
    fp = fopen("练习2-8	计算摄氏温度.c", "w");
    fclose(fp);
    fp = fopen("练习2-9	整数四则运算.c", "w");
    fclose(fp);
    fp = fopen("练习2-10 计算分段函数.c", "w");
    fclose(fp);
    fp = fopen("练习2-11 计算分段函数.c", "w");
    fclose(fp);
    fp = fopen("练习2-12 输出华氏.c", "w");
    fclose(fp);
    fp = fopen("练习2-13 求N分之一序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("练习2-14 求奇数分之一序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("练习2-15 求简单交错序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("练习2-17 生成3的乘方表.c", "w");
    fclose(fp);
    fp = fopen("练习2-18 求组合数.c", "w");
    fclose(fp);
    fp = fopen("习题2-1	求整数均值.c", "w");
    fclose(fp);
    fp = fopen("习题2-2	阶梯电价.c", "w");
    fclose(fp);
    fp = fopen("习题2-3	求平方与倒数序列的部分和.c", "w");
    fclose(fp);
    fp = fopen("习题2-4	求交错序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("习题2-5	求平方根序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("习题2-6	求阶乘序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("练习3-2	计算符号函数的值.c", "w");
    fclose(fp);
    fp = fopen("练习3-3	统计学生平均成绩与及格人数.c", "w");
    fclose(fp);
    fp = fopen("练习3-4	统计字符.c", "w");
    fclose(fp);
    fp = fopen("练习3-5	输出闰年.c", "w");
    fclose(fp);
    fp = fopen("练习3-7	成绩转换.c", "w");
    fclose(fp);
    fp = fopen("练习3-8	查询水果价格.c", "w");
    fclose(fp);
    fp = fopen("习题3-1	比较大小.c", "w");
    fclose(fp);
    fp = fopen("习题3-2	高速公路超速处罚.c", "w");
    fclose(fp);
    fp = fopen("习题3-3	出租车计价.c", "w");
    fclose(fp);
    fp = fopen("习题3-4	统计学生成绩.c", "w");
    fclose(fp);
    fp = fopen("习题3-5	三角形判断.c", "w");
    fclose(fp);
    fp = fopen("练习4-3	求给定精度的简单交错序列部分和.c", "w");
    fclose(fp);
    fp = fopen("练习4-6	猜数字游戏.c", "w");
    fclose(fp);
    fp = fopen("练习4-7	求e的近似值.c", "w");
    fclose(fp);
    fp = fopen("练习4-10 找出最小值.c", "w");
    fclose(fp);
    fp = fopen("练习4-11 统计素数并求和.c", "w");
    fclose(fp);
    fp = fopen("习题4-1 求奇数和.c", "w");
    fclose(fp);
    fp = fopen("习题4-2 求幂级数展开的部分和.c", "w");
    fclose(fp);
    fp = fopen("习题4-3 求分数序列前N项和.c", "w");
    fclose(fp);
    fp = fopen("习题4-4 特殊a串数列求和.c", "w");
    fclose(fp);
    fp = fopen("习题4-5 换硬币.c", "w");
    fclose(fp);
    fp = fopen("习题4-6 水仙花数.c", "w");
    fclose(fp);
    fp = fopen("习题4-7 最大公约数和最小公倍数.c", "w");
    fclose(fp);
    fp = fopen("习题4-8 高空坠球.c", "w");
    fclose(fp);
    fp = fopen("习题4-9 打印菱形图案.c", "w");
    fclose(fp);
    fp = fopen("习题4-10 猴子吃桃问题.c", "w");
    fclose(fp);
    fp = fopen("习题4-11 兔子繁衍问题.c", "w");
    fclose(fp);
    fp = fopen("习题6-7 简单计算器.c", "w");
    fclose(fp);
    fp = fopen("习题6-8 统计一行文本的单词个数.c", "w");
    fclose(fp);
    fp = fopen("练习7-2 求最大值及其下标.c", "w");
    fclose(fp);
    fp = fopen("练习7-3 将数组中的数逆序存放.c", "w");
    fclose(fp);
    fp = fopen("练习7-4 找出不是两个数组共有的元素.c", "w");
    fclose(fp);
    fp = fopen("练习7-7 矩阵运算.c", "w");
    fclose(fp);
    fp = fopen("练习7-8 方阵循环右移.c", "w");
    fclose(fp);
    fp = fopen("练习7-9 计算天数.c", "w");
    fclose(fp);
    fp = fopen("练习7-10 查找指定字符.c", "w");
    fclose(fp);
    fp = fopen("练习7-11 字符串逆序.c", "w");
    fclose(fp);
    fp = fopen("习题7-1 选择法排序.c", "w");
    fclose(fp);
    fp = fopen("习题7-2 求一批整数中出现最多的个位数字.c", "w");
    fclose(fp);
    fp = fopen("习题7-3 判断上三角矩阵.c", "w");
    fclose(fp);
    fp = fopen("习题7-4 求矩阵各行元素之和.c", "w");
    fclose(fp);
    fp = fopen("习题7-5 找鞍点.c", "w");
    fclose(fp);
    fp = fopen("习题7-6 统计大写辅音字母.c", "w");
    fclose(fp);
    fp = fopen("习题7-7 字符串替换.c", "w");
    fclose(fp);
    fp = fopen("习题7-8 字符串转换成十进制整数.c", "w");
    fclose(fp);
    fp = fopen("习题8-7 字符串排序.c", "w");
    fclose(fp);
    fp = fopen("习题8-10 输出学生成绩.c", "w");
    fclose(fp);
    fp = fopen("习题9-1	时间换算.c", "w");
    fclose(fp);
    fp = fopen("习题9-3	平面向量加法.c", "w");
    fclose(fp);
    fp = fopen("习题9-4	查找书籍.c", "w");
    fclose(fp);
    fp = fopen("习题9-5	通讯录排序.c", "w");
    fclose(fp);
    return 0;
}
